# Generated by Django 5.0.6 on 2026-06-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('course', 'Course'), ('plan', 'Subscription Plan')], max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
